# MySQLデータベースサービス
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - "./docker/db:/var/lib/mysql"
    networks:
      - swing-net

  # フロントエンドアプリケーションサービス
  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - '8000'
    networks:
      - swing-net

  # バックエンドアプリケーションサービス
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app # ソースコードをコンテナにマウント
    expose:
      - "3000"
    depends_on:
      - db # dbサービスが起動後にbackendを起動
      - redis # redisサービスが起動後にbackendを起動
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    env_file:
      - .env
    command: bash -c "cron && rails server -b '0.0.0.0' -p 3000"
    networks:
      - swing-net

  # Redisキャッシュサービス
  redis:
    image: "redis:latest"
    expose:
      - "6379"
    volumes:
      - "./docker/redis/data:/data"
    networks:
      - swing-net

  # networking
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - swing-net

networks:
  swing-net: