# MySQLデータベースサービス
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - "./docker/db:/var/lib/mysql"

  # フロントエンドアプリケーションサービス
  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '8000:8000'

  # バックエンドアプリケーションサービス
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app # ソースコードをコンテナにマウント
    ports:
      - "3000:3000"
    depends_on:
      - db # dbサービスが起動後にbackendを起動
      - redis # redisサービスが起動後にbackendを起動
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    env_file:
      - .env
    command: bash -c "cron && rails server -b '0.0.0.0' -p 3000"

  # Redisキャッシュサービス
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis/data:/data"