# MySQLデータベースサービス
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - mysql-db:/var/lib/mysql # データ永続化用ボリューム

  # Redisキャッシュサービス
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # バックエンドアプリケーションサービス
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app # ソースコードをコンテナにマウント
    ports:
      - "3000:3000"
    depends_on:
      - db # dbサービスが起動後にbackendを起動
      - redis # redisサービスが起動後にbackendを起動
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    env_file:
      - .env

  # フロントエンドアプリケーションサービス
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app # ソースコードをコンテナにマウント
      - /app/node_modules # node_modulesをコンテナにマウント
    environment:
      - NODE_ENV=development # Node.jsの実行環境
      # - WATCHPACK_POLLING=true # ホットリロード
      - API_KEY=${API_KEY} # 外部サービスへのアクセス用
    command: npm run dev # 開発サーバーを起動
    ports:
      - '8000:8000'

# 永続ボリューム
volumes:
  mysql-db:
    driver: local