name: CD Pipeline

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/swing-frontend:latest ./frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/swing-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/swing-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/swing-backend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          export COMPOSE_HTTP_TIMEOUT=600
          cd Swing
          docker-compose down
          docker-compose pull
          
          # 起動ログを確認するために各コンテナを順次起動
          docker-compose up -d db
          docker-compose logs db

          docker-compose up -d redis
          docker-compose logs redis

          docker-compose up -d backend
          docker-compose logs backend

          docker-compose up -d frontend
          docker-compose logs frontend
          
          docker-compose up -d nginx
          docker-compose logs nginx
  
