name: Ruby Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Run RuboCop
      run: docker-compose run backend bundle exec rubocop

    - name: Clean up
      run: docker-compose down